services:
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wp_db_password
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '256M');
        define('WP_POST_REVISIONS', 3);
        define('MEDIA_TRASH', true);
        define('EMPTY_TRASH_DAYS', 7);
        define('WP_MAX_UPLOAD_SIZE', '32M');
    secrets:
      - wp_db_password
    networks:
      - traefik-public
      - wp_internal
    deploy:
      placement:
        constraints:
          - node.hostname == ${WP_NODE_HOSTNAME}
      labels:
        - traefik.backend.loadbalancer.swarm=true
        - traefik.frontend.rule=Host:gen.my.kipya-connect.com
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http,https
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https,http
        - traefik.backend.loadbalancer.stickiness=true

  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/wp_db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
      - wp_db_password
    networks:
      - wp_internal
    deploy:
      placement:
        constraints:
          - node.hostname == ${WP_NODE_HOSTNAME}

volumes:
  wp_data:
  db_data:

networks:
  traefik-public:
    external: true
  wp_internal:
    driver: overlay
    internal: true

secrets:
  wp_db_password:
    external: true
  db_root_password:
    external: true